- hosts: all
  roles:
    - debian-packaging
  tasks:
    - name: Upload debian packages
      become: yes
      synchronize:
        src: "{{ zuul.project.src_dir }}/../*.deb"
        dest: '{{ zuul.executor.log_root }}/debian/'
        mode: pull
        recursive: false
        verify_host: true
        rsync_opts: []
