---
- name: "Run flake8"
  shell: find * -name "*.py" | xargs --no-run-if-empty flake8
  register: _flake8
  ignore_errors: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Set linter failure to true
  set_fact:
    linter_failure: true
  when: _flake8.rc
