---
- name: Run golint
  shell: >
    find * -name "*.go" | xargs --no-run-if-empty golint -set_exit_status
  register: _golint
  ignore_errors: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Set linter failure to true
  set_fact:
    linter_failure: true
  when: _golint.rc
