---
- name: Run yamllint
  shell: >
    find * -name "*.yml" -or -name "*.yaml" |
        xargs --no-run-if-empty yamllint -d relaxed
  register: _yamllint
  ignore_errors: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Set linter failure to true
  set_fact:
    linter_failure: true
  when: _yamllint.rc
