---
- hosts: all
  tasks:
    - name: Launch the containers in AIO config
      command: "docker-compose -f docker-compose-aio.yaml up -d"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"

    - name: Check that sbc is listed in Consul services (aio)
      shell: "docker-compose exec -T consul consul catalog services|grep '^sbc$'"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"
      register: result_sbc
      until: result_sbc.rc == 0
      retries: 6
      delay: 10

    - name: Run tests (aio)
      shell: "docker-compose exec -T wazo-tester pytest -v -k \" not router and not failover\" /tests/"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"

    - name: Stop the containers (aio)
      command: "docker-compose -f docker-compose.yaml down"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"

    - name: Launch the containers
      command: "docker-compose -f docker-compose.yaml up -d"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"

    - name: Check that sbc is listed in Consul services
      shell: "docker-compose exec -T consul consul catalog services|grep '^sbc$'"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"
      register: result_sbc
      until: result_sbc.rc == 0
      retries: 6
      delay: 10

    - name: Check that router is listed in Consul services
      shell: "docker-compose exec -T consul consul catalog services|grep '^router$'"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"
      register: result_router
      until: result_router.rc == 0
      retries: 6
      delay: 10

    - name: Check that wazo-router-confd is listed in Consul services
      shell: "docker-compose exec -T consul consul catalog services|grep '^wazo-router-confd$'"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"
      register: result_confd
      until: result_confd.rc == 0
      retries: 6
      delay: 10

    - name: Check that rtp is listed in Consul services
      shell: "docker-compose exec -T consul consul catalog services|grep '^rtp$'"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"
      register: result_rtp
      until: result_rtp.rc == 0
      retries: 6
      delay: 10

    - name: List Consul services
      shell: "docker-compose exec -T consul consul catalog services"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"

    - name: Run tests
      shell: "docker-compose exec -T wazo-tester pytest -v /tests/"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"

    - name: Stop the containers
      command: "docker-compose -f docker-compose.yaml down"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-c4"
