- name: Download orig sources if needed or update changelog
  shell: "if grep -q get-orig-source debian/rules; then debian/rules get-orig-source; tar xvf ../*.tar* --strip 1 --exclude 'debian/*'; else dch -b -v $(../xivo-ci/bin/wazo-package-version $(wget -q -O - http://mirror.wazo.community/version/unstable)) --distribution $distribution --force-distribution \"$(git log -1 HEAD --pretty=format:%s)\"; fi"
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Build debian packages
  shell: "debuild -d --no-tgz-check --no-lintian --preserve-envvar=MAKEFLAGS --preserve-envvar=PATH -us -uc -ui --no-sign"
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Install packages
  shell: "apt install -y ../*.deb"
  become: yes
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: List content of debian packages
  shell: "for p in $(ls *.deb); do echo \"=== $p ===\"; dpkg -c $p; done"
  args:
    chdir: "{{ zuul.project.src_dir }}/.."

- name: Run Lintian
  shell: "lintian *.deb"
  args:
    chdir: "{{ zuul.project.src_dir }}/.."

- name: Create Packages file
  shell: "dpkg-scanpackages . > Packages"
  args:
    chdir: "{{ zuul.project.src_dir }}/.."
