- name: Install build essential packages
  become: yes
  apt:
    name:
      - 'devscripts'
      - 'dirmngr'
      - 'build-essential'
      - 'autopkgtest'
    update_cache: true
    state: present
  vars:
    DEBIAN_FRONTEND: noninteractive

- name: Import Wazo gpg key
  become: yes
  apt_key:
    keyserver: hkp://keys.gnupg.net
    id: 3F1BF7FC527FBC6A

- name: Configure Wazo dev repository
  become: yes
  apt_repository:
    repo: deb http://mirror.wazo.community/debian/ wazo-dev-buster main
    state: present

- name: Copy script to validate versions
  copy:
    src: scripts/check-versions.sh
    dest: /tmp/check-versions.sh
    mode: 0755

- include_tasks: build-package.yaml
  loop: "{{ zuul.projects.values() | list }}"

- name: Create Packages file
  shell: "dpkg-scanpackages . > Packages"
  args:
    chdir: "{{ zuul.project.src_dir }}/.."
