- name: Download orig sources if needed
  shell: if grep -q get-orig-source debian/rules; then debian/rules get-orig-source; fi
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Build binary debian packages
  command: debuild -d --no-tgz-check --no-lintian --preserve-envvar=MAKEFLAGS --preserve-envvar=PATH -us -uc -ui --no-sign
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: List content of debian packages
  shell: "for p in $(ls *.deb); do echo \"=== $p ===\"; dpkg -c $p; done"
  args:
    chdir: "{{ zuul.project.src_dir }}/.."
