---
- hosts: all
  tasks:
    - name: Install Ansible
      become: yes
      apt: name={{ item }} state=installed
      with_items:
        - ansible

    - name: Install postgresql ansible module from galaxy # noqa 301
      become: yes
      command: "ansible-galaxy install -r requirements-postgresql.yml"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-ansible"
